openapi: 3.0.0
info:
  version: 1.0-SNAPSHOT-oas3
  title: ?lesson 1?
servers:
  - url: /v1
paths:
  /simple:
    get:
      x-ncr-mock: '{ "result": 43 }'
      description: Simple get mock.
      operationId: getSimple
      responses:
        '200':
          description: empty response
          content:
            application/json:
              schema:
                type: string