openapi: 3.0.0
info:
  version: 1.0-SNAPSHOT-oas3
  title: lesson 8
paths:
  /chat:
    get:
      security: []
      operationId: chat
      x-ncr-socket:
        enabled: ''
      responses:
        default:
          description: lesson8test
servers:
  - url: /v1