openapi: 3.0.0
info:
  version: 1.0-SNAPSHOT-oas3
  title: lesson 9
paths:
  /producer:
    post:
      description: send messages
      operationId: sendMessage
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Message'
        required: true
      responses:
        '200':
          description: response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Message'
  /consumer:
    get:
      description: receive messages
      operationId: receiveMessage
      responses:
        '200':
          description: response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Message'
servers:
  - url: /v1
components:
  schemas:
    Message:
      type: object
      properties:
        content:
          type: string