version: '3'
services:
  iso-server:
    build: .
    ports:
      - "8080:8080"
      - "18081:18081"
      - "8000:8000"
    environment:
      TX_INFINITY_DEVELOPMENT: "win"
      SWAGGER_UI_ENABLED: "true"
      ISO_MODE_ENABLED: "true"
      METRICS_ENABLED: "true"
      ISO_HOST: "iso-server"
      ISO_PORT: "8080"
    volumes:
      - ./resources/iso-server:/opt/tx-apitoolkit-service/app
  iso-rest-client:
    build: .
    ports:
      - "9090:8080"
      - "19091:18081"
    environment:
      TX_INFINITY_DEVELOPMENT: "win"
      SWAGGER_UI_ENABLED: "true"
      ISO_HOST: "iso-server"
      ISO_PORT: "8080"
      ISO_MLI: "3"
    volumes:
      - ./resources/iso-rest-client:/opt/tx-apitoolkit-service/app
  apitoolkit-ui:
    image: ncr-csp-docker-snapshots.jfrog.io/tx-apitoolkit-ui:2.4.0-latest
    ports:
      - "8090:8090"