version: '3'
services:
  lesson12:
    build: .
    ports:
    - "8080:8080"
    - "8000:8000"
    - "18081:18081"
    environment:
      - "TX_INFINITY_DEVELOPMENT=win"
      - "IBM_HOST=ibmmq"
      - "IBM_PORT=1414"
    volumes:
    - ".:/opt/tx-apitoolkit-service/app"
  apitoolkit-ui:
    image: ncr-csp-docker-snapshots.jfrog.io/tx-apitoolkit-ui:2.4.0-latest
    ports:
    - "8090:8090"
  ibmmq:
    image: ibmcom/mq:latest
    environment:
    - "LICENSE=accept"
    - "MQ_QMGR_NAME=QM1"
    - "MQ_APP_PASSWORD=passw0rd"
    ports:
    - "1414:1414"
    - "9443:9443"
