openapi: 3.0.0
info:
  version: 1.0-SNAPSHOT
  title: lesson 12
servers:
  - url: /v1
paths:
  /echoCopybook:
    post:
      description: echoCopybook
      operationId: echoCopybook
      requestBody:
        content:
          application/json:
            schema:
              type: object
        required: true
      responses:
        default:
          description: simple