openapi: 3.0.0
info:
  version: 1.0-SNAPSHOT-oas3
  title: lesson 10
paths:
  /template:
    get:
      description: produce json from template
      operationId: getJsonFromTemplate
      responses:
        '200':
          description: response
          content:
            application/json:
              schema:
                type: object
servers:
  - url: /v1